### ISSUE TITLE
OAGR can die if persistent failure to communicate with OAG

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#64]
2015-01-20 05:34:41 Processing job 977e491d99674dc59836a0655e685c8d
Timeout: None
Back Off Factor: 1
Max Back Off: 120
Max Tries per Identifier: None
Batch Size: 100
1 received; 0 errors; 9 pending
9 due; requesting in 1 batches
Processing batch  (retry)
(retry)
(retry)
(retry)
(retry)
(retry)
(retry)
(retry)
(retry)
(retry)
Traceback (most recent call last):
  File "magnificent-octopus/octopus/modules/oag/runner.py", line 29, in <module>
    jr.run()
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/modules/oag/oagr.py", line 83, in run
    self.cycle_state(state)
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/modules/oag/oagr.py", line 48, in cycle_state
    self.client.cycle(state, self.oag_throttle, self.verbose)
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/modules/oag/client.py", line 229, in cycle
    result = self._query(batch)
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/modules/oag/client.py", line 256, in _query
    resp.raise_for_status()
  File "/opt/oacwellcome/local/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error

**Comment by richard-jones** [comment]
Actions:

1. Get OAGR to use the new incremental retry code on the http level
2. Don't die in the event of a failed HTTP request to OAG.  Instead just carry on - the job will get picked up again on the next run

**Comment by richard-jones** [comment]
This has now been theoretically fixed, although I am going to leave this issue open to remind us to monitor the process in-the-wild to ensure it doesn't happen again.

Certainly, since implementing the changes above, it has not recurred in my dev environment.

**Comment by richard-jones** [comment]
See #66 for how to implement email-based error handler

**Comment by richard-jones** [comment]
I've just checked this in.

@emanuil-tolev - I'm not sure really how best to test this, do you want to just check that it works on the live box with debug=False, then I'll close this off?

**Comment by emanuil-tolev** [comment]
Just set DEBUG=False in local.cfg and put ```raise Exception("intentional")``` in the OAGR runner init.

**Comment by emanuil-tolev** [comment]
oh yeah, and you'll need the real email details, heh... sent over email to you!
